import { createClient, SupabaseClient } from '@supabase/supabase-js';
import { Chamado, SupabaseConfig } from '../types/index.ts';

const STORAGE_KEY_CONFIG = 'manutencao_supabase_config_v1';
const STORAGE_KEY_CHAMADOS = 'manutencao_chamados_local_v1';

export const SUPABASE_SQL_SCHEMA = `-- ==============================================================================
-- SISTEMA DE CHAMADOS DE MANUTENÇÃO - SUPABASE COMPLETO
-- TABELA RELACIONAL + POLÍTICAS DE RLS + BUCKET DE ARMAZENAMENTO (STORAGE) + POLÍTICAS
-- ==============================================================================

-- ------------------------------------------------------------------------------
-- 1. TABELA PRINCIPAL: chamados
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.chamados (
  id TEXT PRIMARY KEY,
  numero BIGINT GENERATED BY DEFAULT AS IDENTITY,
  titulo TEXT NOT NULL,
  equipamento TEXT NOT NULL,
  setor TEXT NOT NULL,
  prioridade TEXT NOT NULL CHECK (prioridade IN ('baixa', 'media', 'alta', 'critica')),
  status TEXT NOT NULL DEFAULT 'aberto' CHECK (status IN ('aberto', 'em_atendimento', 'encerrado')),
  descricao_problema TEXT NOT NULL,
  sintomas TEXT,
  parou_producao BOOLEAN NOT NULL DEFAULT false,
  aberto_por TEXT NOT NULL,
  aberto_em TIMESTAMPTZ NOT NULL DEFAULT now(),
  em_atendimento_por TEXT,
  em_atendimento_em TIMESTAMPTZ,
  solucao_descricao TEXT,
  causa_raiz TEXT,
  pecas_utilizadas TEXT,
  tempo_gasto_minutos INTEGER,
  testes_realizados TEXT,
  encerrado_por TEXT,
  encerrado_em TIMESTAMPTZ,
  anexos TEXT[], -- Links de fotos/documentos armazenados no Storage
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ------------------------------------------------------------------------------
-- 2. HABILITAR ROW LEVEL SECURITY (RLS) NA TABELA
-- ------------------------------------------------------------------------------
ALTER TABLE public.chamados ENABLE ROW LEVEL SECURITY;

-- Políticas de acesso na tabela 'chamados':
DROP POLICY IF EXISTS "Leitura de chamados por todos" ON public.chamados;
CREATE POLICY "Leitura de chamados por todos"
  ON public.chamados
  FOR SELECT
  TO anon, authenticated
  USING (true);

DROP POLICY IF EXISTS "Insercao de chamados por operadores e autenticados" ON public.chamados;
CREATE POLICY "Insercao de chamados por operadores e autenticados"
  ON public.chamados
  FOR INSERT
  TO anon, authenticated
  WITH CHECK (true);

DROP POLICY IF EXISTS "Atualizacao de chamados por mecanicos e operadores" ON public.chamados;
CREATE POLICY "Atualizacao de chamados por mecanicos e operadores"
  ON public.chamados
  FOR UPDATE
  TO anon, authenticated
  USING (true)
  WITH CHECK (true);

-- Índices de alto desempenho
CREATE INDEX IF NOT EXISTS idx_chamados_aberto_em ON public.chamados (aberto_em DESC);
CREATE INDEX IF NOT EXISTS idx_chamados_status ON public.chamados (status);
CREATE INDEX IF NOT EXISTS idx_chamados_equipamento ON public.chamados (equipamento);

-- ------------------------------------------------------------------------------
-- 3. BUCKET DE ARMAZENAMENTO (SUPABASE STORAGE)
-- ------------------------------------------------------------------------------
-- Criar bucket 'manutencao-anexos' para fotos de máquinas e ordens de serviço
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'manutencao-anexos',
  'manutencao-anexos',
  true,
  10485760, -- limite de 10MB por arquivo
  ARRAY['image/jpeg', 'image/png', 'image/webp', 'application/pdf']
)
ON CONFLICT (id) DO UPDATE SET
  public = true,
  file_size_limit = 10485760,
  allowed_mime_types = ARRAY['image/jpeg', 'image/png', 'image/webp', 'application/pdf'];

-- ------------------------------------------------------------------------------
-- 4. POLÍTICAS DE SEGURANÇA E ARMAZENAMENTO NO SUPABASE STORAGE (storage.objects)
-- ------------------------------------------------------------------------------

-- Política de Leitura/Download Público de arquivos do bucket:
DROP POLICY IF EXISTS "Permitir leitura publica de anexos de manutencao" ON storage.objects;
CREATE POLICY "Permitir leitura publica de anexos de manutencao"
  ON storage.objects
  FOR SELECT
  TO anon, authenticated
  USING (bucket_id = 'manutencao-anexos');

-- Política de Upload de Fotos/Anexos:
DROP POLICY IF EXISTS "Permitir upload de fotos e anexos do chamado" ON storage.objects;
CREATE POLICY "Permitir upload de fotos e anexos do chamado"
  ON storage.objects
  FOR INSERT
  TO anon, authenticated
  WITH CHECK (bucket_id = 'manutencao-anexos');

-- Política de Atualização de arquivos:
DROP POLICY IF EXISTS "Permitir atualizacao de anexos do chamado" ON storage.objects;
CREATE POLICY "Permitir atualizacao de anexos do chamado"
  ON storage.objects
  FOR UPDATE
  TO anon, authenticated
  USING (bucket_id = 'manutencao-anexos')
  WITH CHECK (bucket_id = 'manutencao-anexos');

-- Política de Exclusão de arquivos:
DROP POLICY IF EXISTS "Permitir exclusao de anexos do chamado" ON storage.objects;
CREATE POLICY "Permitir exclusao de anexos do chamado"
  ON storage.objects
  FOR DELETE
  TO anon, authenticated
  USING (bucket_id = 'manutencao-anexos');
`;

const INITIAL_DEMO_CHAMADOS: Chamado[] = [
  {
    id: 'ch-101',
    numero: 1041,
    titulo: 'Vazamento contínuo de óleo no cilindro de prensagem',
    equipamento: 'Prensa Hidráulica 250T (PH-03)',
    setor: 'Estamparia Pesada',
    prioridade: 'alta',
    status: 'aberto',
    descricao_problema: 'Durante o ciclo de estampagem das chapas de 3mm, o operador notou gotejamento volumoso de fluido hidráulico pelo retentor da haste principal. Pressão do manômetro oscilando entre 160 e 190 bar.',
    sintomas: 'Gotejamento sob a carcaça, cheiro característico de óleo superaquecido, ruído de cavitação na bomba auxiliar.',
    parou_producao: true,
    aberto_por: 'Carlos Silva (operador)',
    aberto_em: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
  },
  {
    id: 'ch-102',
    numero: 1040,
    titulo: 'Vibração excessiva e ruído anormal no spindle',
    equipamento: 'Centro de Usinagem CNC (MC-02)',
    setor: 'Usinagem de Precisão',
    prioridade: 'critica',
    status: 'em_atendimento',
    descricao_problema: 'Ao atingir rotação acima de 4.500 RPM na fase de acabamento, o eixo árvore apresentou forte vibração ressonante e alarme de temperatura no mancal frontal (68°C). Operação suspensa para prevenir dano.',
    sintomas: 'Ruído estridente em alta rotação, rugosidade acima do limite na peça usinada, alarme térmico E-402.',
    parou_producao: true,
    aberto_por: 'Carlos Silva (operador)',
    aberto_em: new Date(Date.now() - 110 * 60 * 1000).toISOString(),
    em_atendimento_por: 'Roberto Mendes (mecanico)',
    em_atendimento_em: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
  },
  {
    id: 'ch-103',
    numero: 1039,
    titulo: 'Alinhamento desalinhado e travamento na esteira de saída',
    equipamento: 'Esteira Transportadora Modular L-04',
    setor: 'Linha de Montagem',
    prioridade: 'media',
    status: 'encerrado',
    descricao_problema: 'A esteira estava patinando com carga completa e desengatando elos na curva intermediária.',
    sintomas: 'Estalos metálicos ao tracionar, redução intermitente de velocidade.',
    parou_producao: false,
    aberto_por: 'Carlos Silva (operador)',
    aberto_em: new Date(Date.now() - 280 * 60 * 1000).toISOString(),
    em_atendimento_por: 'Roberto Mendes (mecanico)',
    em_atendimento_em: new Date(Date.now() - 200 * 60 * 1000).toISOString(),
    solucao_descricao: 'Realizado alinhamento dos rolos guia, ajuste de tensão do esticador pneumático e substituição de 4 elos desgastados da corrente plástica de tração. Feita lubrificação completa com graxa alimentícia.',
    causa_raiz: 'Acúmulo de partículas na guia lateral gerando atrito e fadiga mecânica nos elos.',
    pecas_utilizadas: '4 elos modulares POM 25mm, 1 spray graxa PTFE',
    tempo_gasto_minutos: 65,
    testes_realizados: 'Teste contínuo a vazio por 15 min e teste com carga máxima por 20 min sem ruídos ou desvios.',
    encerrado_por: 'Roberto Mendes (mecanico)',
    encerrado_em: new Date(Date.now() - 95 * 60 * 1000).toISOString(),
  }
];

export function getStoredConfig(): { url: string; anonKey: string } {
  try {
    const saved = localStorage.getItem(STORAGE_KEY_CONFIG);
    if (saved) {
      const parsed = JSON.parse(saved);
      if (parsed.url && parsed.anonKey) {
        return parsed;
      }
    }
  } catch (e) {
    console.error('Erro ao ler config Supabase do localStorage', e);
  }

  // Fallback to Vite env variables
  const envUrl = (import.meta.env.VITE_SUPABASE_URL as string) || '';
  const envKey = (import.meta.env.VITE_SUPABASE_ANON_KEY as string) || '';

  return {
    url: envUrl.includes('your-project') ? '' : envUrl,
    anonKey: envKey.includes('your-anon-key') ? '' : envKey,
  };
}

export function saveStoredConfig(url: string, anonKey: string) {
  localStorage.setItem(STORAGE_KEY_CONFIG, JSON.stringify({ url: url.trim(), anonKey: anonKey.trim() }));
}

export function clearStoredConfig() {
  localStorage.removeItem(STORAGE_KEY_CONFIG);
}

let activeClient: SupabaseClient | null = null;
let lastUrl = '';
let lastKey = '';

export function getSupabaseClient(): SupabaseClient | null {
  const { url, anonKey } = getStoredConfig();
  if (!url || !anonKey) {
    return null;
  }
  if (activeClient && lastUrl === url && lastKey === anonKey) {
    return activeClient;
  }
  try {
    activeClient = createClient(url, anonKey, {
      auth: { persistSession: false },
    });
    lastUrl = url;
    lastKey = anonKey;
    return activeClient;
  } catch (err) {
    console.error('Falha ao inicializar cliente Supabase:', err);
    return null;
  }
}

// Local Storage helpers for chamados
export function getLocalChamados(): Chamado[] {
  try {
    const data = localStorage.getItem(STORAGE_KEY_CHAMADOS);
    if (data) {
      return JSON.parse(data);
    }
  } catch (e) {
    console.error('Erro ao carregar chamados locais', e);
  }
  // Initialize with realistic seed if empty
  localStorage.setItem(STORAGE_KEY_CHAMADOS, JSON.stringify(INITIAL_DEMO_CHAMADOS));
  return INITIAL_DEMO_CHAMADOS;
}

export function saveLocalChamados(chamados: Chamado[]) {
  try {
    localStorage.setItem(STORAGE_KEY_CHAMADOS, JSON.stringify(chamados));
  } catch (e) {
    console.error('Erro ao salvar chamados locais', e);
  }
}

// Test Supabase connectivity
export async function testSupabaseConnection(url: string, anonKey: string): Promise<{ success: boolean; message: string; tableExists: boolean }> {
  if (!url || !anonKey) {
    return { success: false, message: 'URL e Chave Anon são obrigatórios.', tableExists: false };
  }
  try {
    const testClient = createClient(url.trim(), anonKey.trim(), { auth: { persistSession: false } });
    
    // Tentar consultar a tabela chamados
    const { data, error } = await testClient
      .from('chamados')
      .select('id')
      .limit(1);

    if (error) {
      if (error.code === '42P01' || error.message?.includes('relation "chamados" does not exist') || error.message?.includes('not found')) {
        return {
          success: true,
          message: 'Conectado ao Supabase! Porém a tabela "chamados" ainda não foi criada. Execute o script SQL no editor do Supabase.',
          tableExists: false,
        };
      }
      return {
        success: false,
        message: `Erro do Supabase (${error.code || 'API'}): ${error.message}`,
        tableExists: false,
      };
    }

    return {
      success: true,
      message: 'Conexão com o Supabase bem-sucedida e tabela "chamados" verificada!',
      tableExists: true,
    };
  } catch (err: any) {
    return {
      success: false,
      message: err.message || 'Falha ao conectar com o endpoint do Supabase.',
      tableExists: false,
    };
  }
}

// Unified repository methods
export async function fetchAllChamados(): Promise<{ chamados: Chamado[]; source: 'supabase' | 'local'; error?: string }> {
  const client = getSupabaseClient();
  if (client) {
    try {
      const { data, error } = await client
        .from('chamados')
        .select('*')
        .order('aberto_em', { ascending: false });

      if (!error && Array.isArray(data)) {
        // If Supabase returned data, update local cache too for offline resilience
        saveLocalChamados(data as Chamado[]);
        return { chamados: data as Chamado[], source: 'supabase' };
      }
      console.warn('Falha na consulta ao Supabase, revertendo para local storage:', error?.message);
    } catch (err: any) {
      console.warn('Erro de rede ou inicialização com Supabase:', err);
    }
  }

  return { chamados: getLocalChamados(), source: 'local' };
}

export async function insertChamado(novo: Omit<Chamado, 'id' | 'numero'>): Promise<{ chamado: Chamado; source: 'supabase' | 'local' }> {
  const localList = getLocalChamados();
  const maxNum = localList.reduce((max, c) => Math.max(max, c.numero || 0), 1040);
  const nextNum = maxNum + 1;
  const newId = `ch-${Date.now()}`;

  const completeChamado: Chamado = {
    ...novo,
    id: newId,
    numero: nextNum,
  };

  const client = getSupabaseClient();
  if (client) {
    try {
      const { data, error } = await client
        .from('chamados')
        .insert([{
          ...completeChamado,
        }])
        .select()
        .single();

      if (!error && data) {
        const saved = data as Chamado;
        // sync to local cache
        saveLocalChamados([saved, ...localList.filter(c => c.id !== saved.id)]);
        return { chamado: saved, source: 'supabase' };
      } else {
        console.error('Erro ao inserir no Supabase, salvando localmente:', error);
      }
    } catch (err) {
      console.error('Erro de conexão com Supabase durante insert:', err);
    }
  }

  // Fallback to local
  const updatedList = [completeChamado, ...localList];
  saveLocalChamados(updatedList);
  return { chamado: completeChamado, source: 'local' };
}

export async function updateChamadoStatus(
  id: string,
  updates: Partial<Chamado>
): Promise<{ chamado: Chamado; source: 'supabase' | 'local' }> {
  const client = getSupabaseClient();
  const localList = getLocalChamados();
  const existing = localList.find(c => c.id === id);

  if (client) {
    try {
      const { data, error } = await client
        .from('chamados')
        .update(updates)
        .eq('id', id)
        .select()
        .single();

      if (!error && data) {
        const updated = data as Chamado;
        const newLocal = localList.map(c => c.id === id ? updated : c);
        saveLocalChamados(newLocal);
        return { chamado: updated, source: 'supabase' };
      }
      console.error('Erro ao atualizar no Supabase:', error);
    } catch (err) {
      console.error('Erro ao atualizar no Supabase via API:', err);
    }
  }

  // Fallback local update
  const updated = { ...(existing || {}), ...updates } as Chamado;
  const newLocal = localList.map(c => c.id === id ? updated : c);
  saveLocalChamados(newLocal);
  return { chamado: updated, source: 'local' };
}

// Push local records to Supabase when connected
export async function syncLocalToSupabase(): Promise<{ count: number; error?: string }> {
  const client = getSupabaseClient();
  if (!client) {
    return { count: 0, error: 'Supabase não está configurado.' };
  }
  const localList = getLocalChamados();
  if (localList.length === 0) {
    return { count: 0 };
  }

  try {
    const { data, error } = await client
      .from('chamados')
      .upsert(localList, { onConflict: 'id' })
      .select();

    if (error) {
      return { count: 0, error: error.message };
    }
    return { count: data?.length || localList.length };
  } catch (err: any) {
    return { count: 0, error: err.message || 'Falha ao sincronizar' };
  }
}
